//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelManagementSystem.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HMSEntities : DbContext
    {
        public HMSEntities()
            : base("name=HMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_guardian> t_guardian { get; set; }
        public virtual DbSet<t_student> t_student { get; set; }
        public virtual DbSet<t_feetransaction> t_feetransaction { get; set; }
        public virtual DbSet<t_salarytransaction> t_salarytransaction { get; set; }
        public virtual DbSet<t_RegisterUser> t_RegisterUser { get; set; }
        public virtual DbSet<t_staff> t_staff { get; set; }
    
        public virtual int CreateStudent(string p_first_name, string p_last_name, string p_address, Nullable<System.DateTime> p_dob, string p_phone, string p_email, string p_gender, Nullable<decimal> p_monthly_fee, string p_school_info, string p_room_no, string p_building_info, string p_guardian_name, string p_guardian_contact_info, string p_guardian_relationship, Nullable<System.DateTime> p_enrollment_date, byte[] p_img_file)
        {
            var p_first_nameParameter = p_first_name != null ?
                new ObjectParameter("p_first_name", p_first_name) :
                new ObjectParameter("p_first_name", typeof(string));
    
            var p_last_nameParameter = p_last_name != null ?
                new ObjectParameter("p_last_name", p_last_name) :
                new ObjectParameter("p_last_name", typeof(string));
    
            var p_addressParameter = p_address != null ?
                new ObjectParameter("p_address", p_address) :
                new ObjectParameter("p_address", typeof(string));
    
            var p_dobParameter = p_dob.HasValue ?
                new ObjectParameter("p_dob", p_dob) :
                new ObjectParameter("p_dob", typeof(System.DateTime));
    
            var p_phoneParameter = p_phone != null ?
                new ObjectParameter("p_phone", p_phone) :
                new ObjectParameter("p_phone", typeof(string));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_genderParameter = p_gender != null ?
                new ObjectParameter("p_gender", p_gender) :
                new ObjectParameter("p_gender", typeof(string));
    
            var p_monthly_feeParameter = p_monthly_fee.HasValue ?
                new ObjectParameter("p_monthly_fee", p_monthly_fee) :
                new ObjectParameter("p_monthly_fee", typeof(decimal));
    
            var p_school_infoParameter = p_school_info != null ?
                new ObjectParameter("p_school_info", p_school_info) :
                new ObjectParameter("p_school_info", typeof(string));
    
            var p_room_noParameter = p_room_no != null ?
                new ObjectParameter("p_room_no", p_room_no) :
                new ObjectParameter("p_room_no", typeof(string));
    
            var p_building_infoParameter = p_building_info != null ?
                new ObjectParameter("p_building_info", p_building_info) :
                new ObjectParameter("p_building_info", typeof(string));
    
            var p_guardian_nameParameter = p_guardian_name != null ?
                new ObjectParameter("p_guardian_name", p_guardian_name) :
                new ObjectParameter("p_guardian_name", typeof(string));
    
            var p_guardian_contact_infoParameter = p_guardian_contact_info != null ?
                new ObjectParameter("p_guardian_contact_info", p_guardian_contact_info) :
                new ObjectParameter("p_guardian_contact_info", typeof(string));
    
            var p_guardian_relationshipParameter = p_guardian_relationship != null ?
                new ObjectParameter("p_guardian_relationship", p_guardian_relationship) :
                new ObjectParameter("p_guardian_relationship", typeof(string));
    
            var p_enrollment_dateParameter = p_enrollment_date.HasValue ?
                new ObjectParameter("p_enrollment_date", p_enrollment_date) :
                new ObjectParameter("p_enrollment_date", typeof(System.DateTime));
    
            var p_img_fileParameter = p_img_file != null ?
                new ObjectParameter("p_img_file", p_img_file) :
                new ObjectParameter("p_img_file", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateStudent", p_first_nameParameter, p_last_nameParameter, p_addressParameter, p_dobParameter, p_phoneParameter, p_emailParameter, p_genderParameter, p_monthly_feeParameter, p_school_infoParameter, p_room_noParameter, p_building_infoParameter, p_guardian_nameParameter, p_guardian_contact_infoParameter, p_guardian_relationshipParameter, p_enrollment_dateParameter, p_img_fileParameter);
        }
    
        public virtual int SearchStudent(string p_first_name, string p_last_name, string p_phone, string p_email, string p_room_no)
        {
            var p_first_nameParameter = p_first_name != null ?
                new ObjectParameter("p_first_name", p_first_name) :
                new ObjectParameter("p_first_name", typeof(string));
    
            var p_last_nameParameter = p_last_name != null ?
                new ObjectParameter("p_last_name", p_last_name) :
                new ObjectParameter("p_last_name", typeof(string));
    
            var p_phoneParameter = p_phone != null ?
                new ObjectParameter("p_phone", p_phone) :
                new ObjectParameter("p_phone", typeof(string));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_room_noParameter = p_room_no != null ?
                new ObjectParameter("p_room_no", p_room_no) :
                new ObjectParameter("p_room_no", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SearchStudent", p_first_nameParameter, p_last_nameParameter, p_phoneParameter, p_emailParameter, p_room_noParameter);
        }
    
        public virtual int FeePaymentApproval(string p_feetran_id, string p_approved_by)
        {
            var p_feetran_idParameter = p_feetran_id != null ?
                new ObjectParameter("p_feetran_id", p_feetran_id) :
                new ObjectParameter("p_feetran_id", typeof(string));
    
            var p_approved_byParameter = p_approved_by != null ?
                new ObjectParameter("p_approved_by", p_approved_by) :
                new ObjectParameter("p_approved_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FeePaymentApproval", p_feetran_idParameter, p_approved_byParameter);
        }
    
        public virtual int RegisterUser(string p_username, string p_password, string p_staff_id, Nullable<System.DateTime> p_create_on)
        {
            var p_usernameParameter = p_username != null ?
                new ObjectParameter("p_username", p_username) :
                new ObjectParameter("p_username", typeof(string));
    
            var p_passwordParameter = p_password != null ?
                new ObjectParameter("p_password", p_password) :
                new ObjectParameter("p_password", typeof(string));
    
            var p_staff_idParameter = p_staff_id != null ?
                new ObjectParameter("p_staff_id", p_staff_id) :
                new ObjectParameter("p_staff_id", typeof(string));
    
            var p_create_onParameter = p_create_on.HasValue ?
                new ObjectParameter("p_create_on", p_create_on) :
                new ObjectParameter("p_create_on", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegisterUser", p_usernameParameter, p_passwordParameter, p_staff_idParameter, p_create_onParameter);
        }
    
        public virtual int UpdateStudentImage(string p_stud_id, byte[] p_img_file)
        {
            var p_stud_idParameter = p_stud_id != null ?
                new ObjectParameter("p_stud_id", p_stud_id) :
                new ObjectParameter("p_stud_id", typeof(string));
    
            var p_img_fileParameter = p_img_file != null ?
                new ObjectParameter("p_img_file", p_img_file) :
                new ObjectParameter("p_img_file", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStudentImage", p_stud_idParameter, p_img_fileParameter);
        }
    
        public virtual int UpdateStudent(string p_stud_id, string p_first_name, string p_last_name, string p_address, Nullable<System.DateTime> p_dob, string p_phone, string p_email, string p_gender, Nullable<decimal> p_monthly_fee, string p_school_info, string p_room_no, string p_building_info, string p_guardian_name, string p_guardian_contact_info, string p_guardian_relationship, Nullable<System.DateTime> p_enrollment_date)
        {
            var p_stud_idParameter = p_stud_id != null ?
                new ObjectParameter("p_stud_id", p_stud_id) :
                new ObjectParameter("p_stud_id", typeof(string));
    
            var p_first_nameParameter = p_first_name != null ?
                new ObjectParameter("p_first_name", p_first_name) :
                new ObjectParameter("p_first_name", typeof(string));
    
            var p_last_nameParameter = p_last_name != null ?
                new ObjectParameter("p_last_name", p_last_name) :
                new ObjectParameter("p_last_name", typeof(string));
    
            var p_addressParameter = p_address != null ?
                new ObjectParameter("p_address", p_address) :
                new ObjectParameter("p_address", typeof(string));
    
            var p_dobParameter = p_dob.HasValue ?
                new ObjectParameter("p_dob", p_dob) :
                new ObjectParameter("p_dob", typeof(System.DateTime));
    
            var p_phoneParameter = p_phone != null ?
                new ObjectParameter("p_phone", p_phone) :
                new ObjectParameter("p_phone", typeof(string));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_genderParameter = p_gender != null ?
                new ObjectParameter("p_gender", p_gender) :
                new ObjectParameter("p_gender", typeof(string));
    
            var p_monthly_feeParameter = p_monthly_fee.HasValue ?
                new ObjectParameter("p_monthly_fee", p_monthly_fee) :
                new ObjectParameter("p_monthly_fee", typeof(decimal));
    
            var p_school_infoParameter = p_school_info != null ?
                new ObjectParameter("p_school_info", p_school_info) :
                new ObjectParameter("p_school_info", typeof(string));
    
            var p_room_noParameter = p_room_no != null ?
                new ObjectParameter("p_room_no", p_room_no) :
                new ObjectParameter("p_room_no", typeof(string));
    
            var p_building_infoParameter = p_building_info != null ?
                new ObjectParameter("p_building_info", p_building_info) :
                new ObjectParameter("p_building_info", typeof(string));
    
            var p_guardian_nameParameter = p_guardian_name != null ?
                new ObjectParameter("p_guardian_name", p_guardian_name) :
                new ObjectParameter("p_guardian_name", typeof(string));
    
            var p_guardian_contact_infoParameter = p_guardian_contact_info != null ?
                new ObjectParameter("p_guardian_contact_info", p_guardian_contact_info) :
                new ObjectParameter("p_guardian_contact_info", typeof(string));
    
            var p_guardian_relationshipParameter = p_guardian_relationship != null ?
                new ObjectParameter("p_guardian_relationship", p_guardian_relationship) :
                new ObjectParameter("p_guardian_relationship", typeof(string));
    
            var p_enrollment_dateParameter = p_enrollment_date.HasValue ?
                new ObjectParameter("p_enrollment_date", p_enrollment_date) :
                new ObjectParameter("p_enrollment_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStudent", p_stud_idParameter, p_first_nameParameter, p_last_nameParameter, p_addressParameter, p_dobParameter, p_phoneParameter, p_emailParameter, p_genderParameter, p_monthly_feeParameter, p_school_infoParameter, p_room_noParameter, p_building_infoParameter, p_guardian_nameParameter, p_guardian_contact_infoParameter, p_guardian_relationshipParameter, p_enrollment_dateParameter);
        }
    
        public virtual int FeePayment(string p_stud_id, Nullable<decimal> p_paid_amount, Nullable<decimal> p_due_amount, string p_paid_for_month, string p_paid_for_year, string p_comments, string p_created_by, string p_created_on)
        {
            var p_stud_idParameter = p_stud_id != null ?
                new ObjectParameter("p_stud_id", p_stud_id) :
                new ObjectParameter("p_stud_id", typeof(string));
    
            var p_paid_amountParameter = p_paid_amount.HasValue ?
                new ObjectParameter("p_paid_amount", p_paid_amount) :
                new ObjectParameter("p_paid_amount", typeof(decimal));
    
            var p_due_amountParameter = p_due_amount.HasValue ?
                new ObjectParameter("p_due_amount", p_due_amount) :
                new ObjectParameter("p_due_amount", typeof(decimal));
    
            var p_paid_for_monthParameter = p_paid_for_month != null ?
                new ObjectParameter("p_paid_for_month", p_paid_for_month) :
                new ObjectParameter("p_paid_for_month", typeof(string));
    
            var p_paid_for_yearParameter = p_paid_for_year != null ?
                new ObjectParameter("p_paid_for_year", p_paid_for_year) :
                new ObjectParameter("p_paid_for_year", typeof(string));
    
            var p_commentsParameter = p_comments != null ?
                new ObjectParameter("p_comments", p_comments) :
                new ObjectParameter("p_comments", typeof(string));
    
            var p_created_byParameter = p_created_by != null ?
                new ObjectParameter("p_created_by", p_created_by) :
                new ObjectParameter("p_created_by", typeof(string));
    
            var p_created_onParameter = p_created_on != null ?
                new ObjectParameter("p_created_on", p_created_on) :
                new ObjectParameter("p_created_on", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FeePayment", p_stud_idParameter, p_paid_amountParameter, p_due_amountParameter, p_paid_for_monthParameter, p_paid_for_yearParameter, p_commentsParameter, p_created_byParameter, p_created_onParameter);
        }
    
        public virtual int UpdateFeePayment(string p_feetran_id, string p_stud_id, Nullable<decimal> p_paid_amount, Nullable<decimal> p_due_amount, string p_paid_for_month, string p_paid_for_year, string p_comments, string p_created_by, string p_created_on)
        {
            var p_feetran_idParameter = p_feetran_id != null ?
                new ObjectParameter("p_feetran_id", p_feetran_id) :
                new ObjectParameter("p_feetran_id", typeof(string));
    
            var p_stud_idParameter = p_stud_id != null ?
                new ObjectParameter("p_stud_id", p_stud_id) :
                new ObjectParameter("p_stud_id", typeof(string));
    
            var p_paid_amountParameter = p_paid_amount.HasValue ?
                new ObjectParameter("p_paid_amount", p_paid_amount) :
                new ObjectParameter("p_paid_amount", typeof(decimal));
    
            var p_due_amountParameter = p_due_amount.HasValue ?
                new ObjectParameter("p_due_amount", p_due_amount) :
                new ObjectParameter("p_due_amount", typeof(decimal));
    
            var p_paid_for_monthParameter = p_paid_for_month != null ?
                new ObjectParameter("p_paid_for_month", p_paid_for_month) :
                new ObjectParameter("p_paid_for_month", typeof(string));
    
            var p_paid_for_yearParameter = p_paid_for_year != null ?
                new ObjectParameter("p_paid_for_year", p_paid_for_year) :
                new ObjectParameter("p_paid_for_year", typeof(string));
    
            var p_commentsParameter = p_comments != null ?
                new ObjectParameter("p_comments", p_comments) :
                new ObjectParameter("p_comments", typeof(string));
    
            var p_created_byParameter = p_created_by != null ?
                new ObjectParameter("p_created_by", p_created_by) :
                new ObjectParameter("p_created_by", typeof(string));
    
            var p_created_onParameter = p_created_on != null ?
                new ObjectParameter("p_created_on", p_created_on) :
                new ObjectParameter("p_created_on", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateFeePayment", p_feetran_idParameter, p_stud_idParameter, p_paid_amountParameter, p_due_amountParameter, p_paid_for_monthParameter, p_paid_for_yearParameter, p_commentsParameter, p_created_byParameter, p_created_onParameter);
        }
    
        public virtual int DeactivateStudent(string p_stud_id, Nullable<System.DateTime> p_inactive_date)
        {
            var p_stud_idParameter = p_stud_id != null ?
                new ObjectParameter("p_stud_id", p_stud_id) :
                new ObjectParameter("p_stud_id", typeof(string));
    
            var p_inactive_dateParameter = p_inactive_date.HasValue ?
                new ObjectParameter("p_inactive_date", p_inactive_date) :
                new ObjectParameter("p_inactive_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeactivateStudent", p_stud_idParameter, p_inactive_dateParameter);
        }
    
        public virtual ObjectResult<SearchStudentResult> SearchStudentFunction(string p_first_name, string p_last_name, string p_phone, string p_email, string p_room_no)
        {
            var p_first_nameParameter = p_first_name != null ?
                new ObjectParameter("p_first_name", p_first_name) :
                new ObjectParameter("p_first_name", typeof(string));
    
            var p_last_nameParameter = p_last_name != null ?
                new ObjectParameter("p_last_name", p_last_name) :
                new ObjectParameter("p_last_name", typeof(string));
    
            var p_phoneParameter = p_phone != null ?
                new ObjectParameter("p_phone", p_phone) :
                new ObjectParameter("p_phone", typeof(string));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_room_noParameter = p_room_no != null ?
                new ObjectParameter("p_room_no", p_room_no) :
                new ObjectParameter("p_room_no", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchStudentResult>("SearchStudentFunction", p_first_nameParameter, p_last_nameParameter, p_phoneParameter, p_emailParameter, p_room_noParameter);
        }
    
        public virtual int CreateStaff(string p_first_name, string p_last_name, string p_address, Nullable<System.DateTime> p_dob, string p_phone, string p_email, string p_gender, Nullable<decimal> p_salary, string p_building_info, string p_guardian_name, string p_guardian_contact_info, string p_guardian_relationship, Nullable<System.DateTime> p_join_date, string p_citizenship_no, byte[] p_img_file)
        {
            var p_first_nameParameter = p_first_name != null ?
                new ObjectParameter("p_first_name", p_first_name) :
                new ObjectParameter("p_first_name", typeof(string));
    
            var p_last_nameParameter = p_last_name != null ?
                new ObjectParameter("p_last_name", p_last_name) :
                new ObjectParameter("p_last_name", typeof(string));
    
            var p_addressParameter = p_address != null ?
                new ObjectParameter("p_address", p_address) :
                new ObjectParameter("p_address", typeof(string));
    
            var p_dobParameter = p_dob.HasValue ?
                new ObjectParameter("p_dob", p_dob) :
                new ObjectParameter("p_dob", typeof(System.DateTime));
    
            var p_phoneParameter = p_phone != null ?
                new ObjectParameter("p_phone", p_phone) :
                new ObjectParameter("p_phone", typeof(string));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_genderParameter = p_gender != null ?
                new ObjectParameter("p_gender", p_gender) :
                new ObjectParameter("p_gender", typeof(string));
    
            var p_salaryParameter = p_salary.HasValue ?
                new ObjectParameter("p_salary", p_salary) :
                new ObjectParameter("p_salary", typeof(decimal));
    
            var p_building_infoParameter = p_building_info != null ?
                new ObjectParameter("p_building_info", p_building_info) :
                new ObjectParameter("p_building_info", typeof(string));
    
            var p_guardian_nameParameter = p_guardian_name != null ?
                new ObjectParameter("p_guardian_name", p_guardian_name) :
                new ObjectParameter("p_guardian_name", typeof(string));
    
            var p_guardian_contact_infoParameter = p_guardian_contact_info != null ?
                new ObjectParameter("p_guardian_contact_info", p_guardian_contact_info) :
                new ObjectParameter("p_guardian_contact_info", typeof(string));
    
            var p_guardian_relationshipParameter = p_guardian_relationship != null ?
                new ObjectParameter("p_guardian_relationship", p_guardian_relationship) :
                new ObjectParameter("p_guardian_relationship", typeof(string));
    
            var p_join_dateParameter = p_join_date.HasValue ?
                new ObjectParameter("p_join_date", p_join_date) :
                new ObjectParameter("p_join_date", typeof(System.DateTime));
    
            var p_citizenship_noParameter = p_citizenship_no != null ?
                new ObjectParameter("p_citizenship_no", p_citizenship_no) :
                new ObjectParameter("p_citizenship_no", typeof(string));
    
            var p_img_fileParameter = p_img_file != null ?
                new ObjectParameter("p_img_file", p_img_file) :
                new ObjectParameter("p_img_file", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateStaff", p_first_nameParameter, p_last_nameParameter, p_addressParameter, p_dobParameter, p_phoneParameter, p_emailParameter, p_genderParameter, p_salaryParameter, p_building_infoParameter, p_guardian_nameParameter, p_guardian_contact_infoParameter, p_guardian_relationshipParameter, p_join_dateParameter, p_citizenship_noParameter, p_img_fileParameter);
        }
    
        public virtual int UpdateStaff(string p_staff_id, string p_first_name, string p_last_name, string p_address, Nullable<System.DateTime> p_dob, string p_phone, string p_email, string p_gender, Nullable<decimal> p_salary, string p_building_info, string p_guardian_name, string p_guardian_contact_info, string p_guardian_relationship, Nullable<System.DateTime> p_join_date, string p_citizenship_no)
        {
            var p_staff_idParameter = p_staff_id != null ?
                new ObjectParameter("p_staff_id", p_staff_id) :
                new ObjectParameter("p_staff_id", typeof(string));
    
            var p_first_nameParameter = p_first_name != null ?
                new ObjectParameter("p_first_name", p_first_name) :
                new ObjectParameter("p_first_name", typeof(string));
    
            var p_last_nameParameter = p_last_name != null ?
                new ObjectParameter("p_last_name", p_last_name) :
                new ObjectParameter("p_last_name", typeof(string));
    
            var p_addressParameter = p_address != null ?
                new ObjectParameter("p_address", p_address) :
                new ObjectParameter("p_address", typeof(string));
    
            var p_dobParameter = p_dob.HasValue ?
                new ObjectParameter("p_dob", p_dob) :
                new ObjectParameter("p_dob", typeof(System.DateTime));
    
            var p_phoneParameter = p_phone != null ?
                new ObjectParameter("p_phone", p_phone) :
                new ObjectParameter("p_phone", typeof(string));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_genderParameter = p_gender != null ?
                new ObjectParameter("p_gender", p_gender) :
                new ObjectParameter("p_gender", typeof(string));
    
            var p_salaryParameter = p_salary.HasValue ?
                new ObjectParameter("p_salary", p_salary) :
                new ObjectParameter("p_salary", typeof(decimal));
    
            var p_building_infoParameter = p_building_info != null ?
                new ObjectParameter("p_building_info", p_building_info) :
                new ObjectParameter("p_building_info", typeof(string));
    
            var p_guardian_nameParameter = p_guardian_name != null ?
                new ObjectParameter("p_guardian_name", p_guardian_name) :
                new ObjectParameter("p_guardian_name", typeof(string));
    
            var p_guardian_contact_infoParameter = p_guardian_contact_info != null ?
                new ObjectParameter("p_guardian_contact_info", p_guardian_contact_info) :
                new ObjectParameter("p_guardian_contact_info", typeof(string));
    
            var p_guardian_relationshipParameter = p_guardian_relationship != null ?
                new ObjectParameter("p_guardian_relationship", p_guardian_relationship) :
                new ObjectParameter("p_guardian_relationship", typeof(string));
    
            var p_join_dateParameter = p_join_date.HasValue ?
                new ObjectParameter("p_join_date", p_join_date) :
                new ObjectParameter("p_join_date", typeof(System.DateTime));
    
            var p_citizenship_noParameter = p_citizenship_no != null ?
                new ObjectParameter("p_citizenship_no", p_citizenship_no) :
                new ObjectParameter("p_citizenship_no", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStaff", p_staff_idParameter, p_first_nameParameter, p_last_nameParameter, p_addressParameter, p_dobParameter, p_phoneParameter, p_emailParameter, p_genderParameter, p_salaryParameter, p_building_infoParameter, p_guardian_nameParameter, p_guardian_contact_infoParameter, p_guardian_relationshipParameter, p_join_dateParameter, p_citizenship_noParameter);
        }
    
        public virtual int UpdateStaffImage(string p_staff_id, byte[] p_img_file)
        {
            var p_staff_idParameter = p_staff_id != null ?
                new ObjectParameter("p_staff_id", p_staff_id) :
                new ObjectParameter("p_staff_id", typeof(string));
    
            var p_img_fileParameter = p_img_file != null ?
                new ObjectParameter("p_img_file", p_img_file) :
                new ObjectParameter("p_img_file", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStaffImage", p_staff_idParameter, p_img_fileParameter);
        }
    
        public virtual int DeactivateStaff(string p_staff_id)
        {
            var p_staff_idParameter = p_staff_id != null ?
                new ObjectParameter("p_staff_id", p_staff_id) :
                new ObjectParameter("p_staff_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeactivateStaff", p_staff_idParameter);
        }
    
        public virtual int UpdateUser(string p_user_id, string p_username, string p_password, string p_staff_id, string p_active)
        {
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            var p_usernameParameter = p_username != null ?
                new ObjectParameter("p_username", p_username) :
                new ObjectParameter("p_username", typeof(string));
    
            var p_passwordParameter = p_password != null ?
                new ObjectParameter("p_password", p_password) :
                new ObjectParameter("p_password", typeof(string));
    
            var p_staff_idParameter = p_staff_id != null ?
                new ObjectParameter("p_staff_id", p_staff_id) :
                new ObjectParameter("p_staff_id", typeof(string));
    
            var p_activeParameter = p_active != null ?
                new ObjectParameter("p_active", p_active) :
                new ObjectParameter("p_active", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUser", p_user_idParameter, p_usernameParameter, p_passwordParameter, p_staff_idParameter, p_activeParameter);
        }
    
        public virtual ObjectResult<GetFeePaymentTransaction_Result> GetFeePaymentTransaction(Nullable<int> p_days_before)
        {
            var p_days_beforeParameter = p_days_before.HasValue ?
                new ObjectParameter("p_days_before", p_days_before) :
                new ObjectParameter("p_days_before", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFeePaymentTransaction_Result>("GetFeePaymentTransaction", p_days_beforeParameter);
        }
    }
}
