//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelManagementSystem.Data
{
    using System;
    
    public partial class SearchStudent
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string roomNo { get; set; }
        public Nullable<decimal> monthly_fee { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string gender { get; set; }
    }
}
