//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_feetransaction
    {
        public string feetran_id { get; set; }
        public string stud_id { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
        public Nullable<decimal> due_amount { get; set; }
        public string paid_for_month { get; set; }
        public string paid_for_year { get; set; }
        public string tran_approved { get; set; }
        public string approved_by { get; set; }
        public string created_by { get; set; }
        public string created_on { get; set; }
        public string comments { get; set; }
    
        public virtual t_student t_student { get; set; }
    }
}
