//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_guardian
    {
        public string guard_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string relationship { get; set; }
        public string stud_id { get; set; }
        public string staff_id { get; set; }
    
        public virtual t_student t_student { get; set; }
        public virtual t_staff t_staff { get; set; }
    }
}
